app:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:dbo;MODE=MSSQLServer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: SA
    password:
    validationQuery: SELECT 1

spring:
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

files:
  path: /Users/aberenguer/temp/test